const movies = [
    {name:'Batman', production_year:'1966', director:'Leslie H. Martinson'},
    {name:'Spider-Man', production_year:'1977', director:'E. W. Swackhamer'},
    {name:'Dr. Strange', production_year:'1978', director:'Philip DeGuere'},
    {name:'Superman', production_year:'1978', director:'Richard Donner'},
    {name:'Captain America', production_year:'1979', director:'Rod Holcomb'},
    {name:'Captain America II: Death Too Soon', production_year:'1979', director:'Iván Nagy'},
    {name:'Superman II', production_year:'1980', director:'Richard Lester'},
    {name:'Superman III', production_year:'1983', director:'Richard Lester'},
    {name:'Supergirl', production_year:'1984', director:'Jeannot Szwarc'},
    {name:'Superman IV: The Quest for Peace', production_year:'1987', director:'Sidney J. Furie'},
    {name:'The Incredible Hulk Returns', production_year:'1988', director:'	Nicholas J. Corea'},

    {name:'The Trial of the Incredible Hulk', production_year:'1989', director:'Bill Bixby'},
    {name:'Batman', production_year:'1989', director:'Tim Burton'},
    {name:'The Punisher', production_year:'1989', director:'Mark Goldblatt'},
    {name:'The Death of the Incredible Hulk', production_year:'1990', director:'Bill Bixby'},
    {name:'Captain America', production_year:'1990', director:'Albert Pyun'},
    {name:'Batman Returns', production_year:'1992', director:'Tim Burton'},
    {name:'Batman Forever', production_year:'1995', director:'Joel Schumacher'},
    {name:'Batman & Robin', production_year:'1997', director:'Joel Schumacher'},
    {name:'Justice League of America', production_year:'1997', director:'Félix Enríquez Alcalá'},
    {name:'Blade', production_year:'1998', director:'Stephen Norrington'},
    {name:'X-Men', production_year:'2000', director:'Bryan Singer'},

    {name:'Blade II', production_year:'2002', director:'Guillermo del Toro'},
    {name:'Spider-Man', production_year:'2002', director:'Sam Raimi'},
    {name:'Daredevil', production_year:'2003', director:'Mark Steven Johnson'},
    {name:'X2: X-Men United', production_year:'2003', director:'Bryan Singer'},
    {name:'Hulk', production_year:'2003', director:'Ang Lee'},
    {name:'The Punisher', production_year:'2004', director:'Jonathan Hensleigh'},
    {name:'Spider-Man 2', production_year:'2004', director:'Sam Raimi'},
    {name:'Catwoman', production_year:'2004', director:'Pitof'},
    {name:'Blade: Trinity', production_year:'2004', director:'David S. Goyer'},
    {name:'Elektra', production_year:'2005', director:'Rob Bowman'},
    {name:'Batman Begins', production_year:'2005', director:'Christopher Nolan'},


    {name:'X-Men: The Last Stand', production_year:'2006', director:'Brett Ratner'},
    {name:'Superman Returns', production_year:'2006', director:'Bryan Singer'},
    {name:'Spider-Man 3', production_year:'2007', director:'Sam Raimi'},
    {name:'Iron Man', production_year:'2008', director:'Jon Favreau'},
    {name:'The Incredible Hulk', production_year:'2008', director:'Louis Leterrier'},
    {name:'The Dark Knight', production_year:'2008', director:'Christopher Nolan'},
    {name:'Punisher: War Zone', production_year:'2008', director:'Lexi Alexander'},
    {name:'X-Men Origins: Wolverine', production_year:'2009', director:'Gavin Hood'},
    {name:'Iron Man 2', production_year:'2010', director:'Jon Favreau'},
    {name:'Thor', production_year:'2011', director:'Kenneth Branagh'},
    {name:'X-Men: First Class', production_year:'2011', director:'Matthew Vaughn'},

    {name:'Green Lantern', production_year:'2011', director:'Martin Campbell'},
    {name:'Captain America: The First Avenger', production_year:'2011', director:'Joe Johnston'},
    {name:'The Avengers', production_year:'2012', director:'Joss Whedon'},
    {name:'The Amazing Spider-Man', production_year:'2012', director:'Marc Webb'},
    {name:'The Dark Knight Rises', production_year:'2012', director:'Christopher Nolan'},
    {name:'Iron Man 3', production_year:'2013', director:'Shane Black'},
    {name:'Man of Steel', production_year:'2013', director:'Zack Snyder'},
    {name:'The Wolverine', production_year:'2013', director:'James Mangold'},
    {name:'Thor: The Dark World', production_year:'2013', director:'Alan Taylor'},
    {name:'Captain America: The Winter Soldier', production_year:'2014', director:'Anthony and Joe Russo'},
    {name:'The Amazing Spider-Man 2', production_year:'2014', director:'Marc Webb'},

    {name:'X-Men: Days of Future Past', production_year:'2014', director:'Bryan Singer'},
    {name:'Guardians of the Galaxy', production_year:'2014', director:'James Gunn'},
    {name:'Avengers: Age of Ultron', production_year:'2015', director:'Joss Whedon'},
    {name:'Ant-Man', production_year:'2015', director:'Peyton Reed'},
    {name:'Deadpool', production_year:'2016', director:'Tim Miller'},
    {name:'Batman v Superman: Dawn of Justice', production_year:'2016', director:'Zack Snyder'},
    {name:'Captain America: Civil War', production_year:'2016', director:'Anthony and Joe Russo'},
    {name:'X-Men: Apocalypse', production_year:'2016', director:'Bryan Singer'},
    {name:'Doctor Strange', production_year:'2016', director:'Scott Derrickson'},
    {name:'Logan', production_year:'2017', director:'James Mangold'},
    {name:'Guardians of the Galaxy Vol. 2', production_year:'2017', director:'James Gunn'},

    {name:'Wonder Woman', production_year:'2017', director:'Patty Jenkins'},
    {name:'Spider-Man: Homecoming', production_year:'2017', director:'Jon Watts'},
    {name:'Thor: Ragnarok', production_year:'2017', director:'Taika Waititi'},
    {name:'Justice League', production_year:'2017', director:'Zack Snyder'},
    {name:'Black Panther', production_year:'2018', director:'Ryan Coogler'},
    {name:'Avengers: Infinity War', production_year:'2018', director:'Anthony and Joe Russo'},
    {name:'Deadpool 2', production_year:'2018', director:'David Leitch'},
    {name:'Ant-Man and the Wasp', production_year:'2018', director:'Peyton Reed'},
    {name:'X-Men: Dark Phoenix', production_year:'2018', director:'Simon Kinberg'},
    {name:'Aquaman', production_year:'2018', director:'James Wan'},
    {name:'Captain Marvel', production_year:'2019', director:'Anna Boden and Ryan Fleck'},
];

exports.seed = function(knex, Promise) {
  return knex('movies').del().then(() => knex('movies').insert(movies));
};
